matrix:
  include:
    - language: c
      compiler:
        - clang
        - gcc
      before_script:
        - cd prime
        - clang -o testclang ./test.c
        - gcc -o testgcc ./test.c
      script:
        - for i in {1..5}; ./testgcc
        - for i in {1..5}; ./testclang
    - language: java
      before_script:
        - cd prime
        - javac Test.java
      script:
        - for i in {1..5}; java Test
    - language: dart
      - stable
      before_script:
        - cd prime
        - dart2native test.dart
      script:
        - for i in {1..5}; ./testdart
    - language: node_js
      node_js:
        - 14
        - 12
        - 10
      before_script:
        - cd prime
      script:
        - for i in {1..5}; node test.js
    - language: python
      python:
        - 2.7
        - 3
      before_script:
        - cd prime
      script:
        - for i in {1..5}; python test.py
    - language: rust
      rust:
        - stable
      before_script:
        - cd prime
        - rustc -o testrust test.rs
      script:
        - for i in {1..5}; ./testrust
    - language: go
      before_script:
        - cd prime
        - go build -o testgo test.go
      script:
        - for i in {1..5}; ./testgo
    - language: php
      php:
        - '5.6'
        - '7.0'
      before_script:
        - cd prime
      script:
        - for i in {1..5}; php ./test.php
